if (~isdeployed)
    addpath /scratch/mkarikom/Packages/export_fig
    addpath /scratch/mkarikom/Packages/ParforProgMon
    
    addpath /scratch/mkarikom/Packages/gpstuff/diag
    addpath /scratch/mkarikom/Packages/gpstuff/dist
    addpath /scratch/mkarikom/Packages/gpstuff/gp
    addpath /scratch/mkarikom/Packages/gpstuff/mc
    addpath /scratch/mkarikom/Packages/gpstuff/misc
    addpath /scratch/mkarikom/Packages/gpstuff/optim
    addpath /scratch/mkarikom/Packages/gpstuff/tests

    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/UMFPACK/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/CHOLMOD/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/AMD/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/COLAMD/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/CCOLAMD/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/CAMD/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/CXSparse/MATLAB/Demo
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/CXSparse/MATLAB/CSparse
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/LDL/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/BTF/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/KLU/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/SPQR/MATLAB
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/RBio/RBio
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/Factorize
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/MESHND
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/LINFACTOR
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/find_components
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/GEE
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/shellgui
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/waitmex
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/spqr_rank
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/spqr_rank/SJget
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/UFcollection
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/SSMULT
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/dimacs10
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/spok
    addpath /scratch/mkarikom/Packages/gpstuff/SuiteSparse-4.4.2/MATLAB_Tools/sparseinv
end